(()=>{
const seoulImg='https://images.unsplash.com/photo-1760016484296-44c5891731b1?auto=format&fit=crop&w=1800&q=82';
const busanImg='https://i.natgeofe.com/n/90d5cd33-572c-4c7c-b57c-d68be7b7fd61/nbeach-busan-online.jpeg';
const hero=document.querySelector('.countdownHero'); if(!hero)return;
const style=document.createElement('style');style.textContent=`
.countdownHero{padding:0!important;background:#281725!important;min-height:430px;color:#fff;border-color:#ffb7d5!important}
.countdownHero:after{display:none}.heroSlides{position:absolute;inset:0;overflow:hidden;border-radius:24px}.heroSlide{position:absolute;inset:0;background-size:cover;background-position:center;opacity:0;transform:scale(1.03);transition:opacity 1.15s ease,transform 6s ease}.heroSlide.on{opacity:1;transform:scale(1)}.heroShade{position:absolute;inset:0;background:linear-gradient(180deg,rgba(25,9,19,.16),rgba(25,9,19,.48) 42%,rgba(25,9,19,.88))}.heroContent{position:relative;z-index:2;padding:22px 18px 17px}.countdownHero .countLabel,.countdownHero .countMeta,.countdownHero .flightTime{color:#ffe1ee}.countdownHero .countBig{color:#fff;text-shadow:0 4px 25px rgba(0,0,0,.3)}.countdownHero .flightStrip{background:rgba(255,255,255,.13);border-color:rgba(255,255,255,.24);backdrop-filter:blur(10px)}.countdownHero .flightCity{color:#fff}.countdownHero .plane{color:#ffc4dc}.heroCity{display:inline-flex;align-items:center;gap:7px;margin-bottom:7px;padding:5px 9px;border-radius:999px;background:rgba(255,255,255,.16);backdrop-filter:blur(7px);font-size:11px;font-weight:900}.heroDots{display:flex;gap:6px;margin-top:10px}.heroDot{width:18px;height:4px;border-radius:99px;background:rgba(255,255,255,.35);transition:.3s}.heroDot.on{background:#fff;width:30px}.weatherWrap{position:relative;z-index:3;padding:0 14px 14px}.weatherHead{display:flex;justify-content:space-between;gap:10px;align-items:center;margin:0 2px 8px;color:#fff}.weatherHead b{font-size:14px}.weatherSwitch{display:flex;gap:5px}.weatherSwitch button{border:1px solid rgba(255,255,255,.3);background:rgba(255,255,255,.13);color:#fff;border-radius:999px;padding:5px 8px;font-size:10px;font-weight:900}.weatherSwitch button.on{background:#fff;color:#9c3d68}.weather5{display:grid;grid-template-columns:repeat(5,minmax(72px,1fr));gap:7px;overflow:auto}.weatherDay{background:rgba(255,255,255,.92);color:#553442;border-radius:13px;padding:9px 7px;text-align:center;min-width:72px}.weatherDate{font-size:10px;color:#8b6878}.weatherIcon{font-size:21px;margin:4px 0}.weatherTemp{font-size:12px;font-weight:900;color:#7f2850}.weatherRain{font-size:9px;color:#8b6878;margin-top:3px}.weatherStatus{font-size:9px;color:#f6d7e5;margin-top:7px;text-align:right}
`;document.head.appendChild(style);
const old=hero.innerHTML;
hero.innerHTML=`<div class="heroSlides"><div class="heroSlide on" style="background-image:url('${seoulImg}')"></div><div class="heroSlide" style="background-image:url('${busanImg}')"></div><div class="heroShade"></div></div><div class="heroContent"><div class="heroCity" id="heroCity">🇰🇷 SEOUL · 首尔</div>${old}<div class="heroDots"><span class="heroDot on"></span><span class="heroDot"></span></div></div><div class="weatherWrap"><div class="weatherHead"><b>未来 5 Days Weather</b><div class="weatherSwitch"><button class="on" data-city="Seoul">首尔</button><button data-city="Busan">釜山</button></div></div><div class="weather5" id="weather5"><div class="weatherDay">Loading…</div></div><div class="weatherStatus" id="weatherStatus">自动更新天气中…</div></div>`;
let slide=0;const slides=hero.querySelectorAll('.heroSlide'),dots=hero.querySelectorAll('.heroDot'),cityEl=hero.querySelector('#heroCity');setInterval(()=>{slide=(slide+1)%2;slides.forEach((x,i)=>x.classList.toggle('on',i===slide));dots.forEach((x,i)=>x.classList.toggle('on',i===slide));cityEl.textContent=slide===0?'🇰🇷 SEOUL · 首尔':'🌊 BUSAN · 釜山'},6500);
const cfg={Seoul:{lat:37.5665,lon:126.9780},Busan:{lat:35.1796,lon:129.0756}};
let weatherCity='Seoul';
function icon(code){if(code===0)return'☀️';if([1,2].includes(code))return'🌤️';if(code===3)return'☁️';if([45,48].includes(code))return'🌫️';if([51,53,55,56,57,61,63,65,66,67,80,81,82].includes(code))return'🌧️';if([71,73,75,77,85,86].includes(code))return'❄️';if([95,96,99].includes(code))return'⛈️';return'🌤️'}
async function loadWeather(city){weatherCity=city;document.querySelectorAll('.weatherSwitch button').forEach(b=>b.classList.toggle('on',b.dataset.city===city));const c=cfg[city],w=document.getElementById('weather5'),st=document.getElementById('weatherStatus');w.innerHTML='<div class="weatherDay">Loading…</div>';try{const url=`https://api.open-meteo.com/v1/forecast?latitude=${c.lat}&longitude=${c.lon}&daily=weather_code,temperature_2m_max,temperature_2m_min,precipitation_probability_max&timezone=Asia%2FSeoul&forecast_days=5`;const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error(r.status);const d=await r.json(),a=d.daily;w.innerHTML=a.time.map((date,i)=>{const dt=new Date(date+'T12:00:00+09:00'),wd=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'][dt.getDay()];return `<div class="weatherDay"><div class="weatherDate">${date.slice(5)} · ${wd}</div><div class="weatherIcon">${icon(a.weather_code[i])}</div><div class="weatherTemp">${Math.round(a.temperature_2m_min[i])}° / ${Math.round(a.temperature_2m_max[i])}°</div><div class="weatherRain">☔ ${a.precipitation_probability_max[i]??0}%</div></div>`}).join('');st.textContent=`${city==='Seoul'?'首尔':'釜山'} · Open-Meteo · 每次打开网页自动刷新 · ${new Date().toLocaleTimeString('en-MY',{hour:'2-digit',minute:'2-digit',timeZone:'Asia/Kuala_Lumpur'})} MYT`}catch(e){w.innerHTML='<div class="weatherDay">天气暂时无法连接</div>';st.textContent='Weather offline · 稍后刷新网页重试'}}
document.querySelectorAll('.weatherSwitch button').forEach(b=>b.onclick=()=>loadWeather(b.dataset.city));loadWeather('Seoul');
})();