(()=>{
const W='https://commons.wikimedia.org/wiki/Special:Redirect/file/';
const slidesData=[
 {city:'BUSAN · 釜山',place:'海云台 · DAY 1',file:'Haeundae beach in Busan.jpg'},
 {city:'BUSAN · 釜山',place:'青沙浦 · DAY 2',file:'Cheongsapo.jpg'},
 {city:'BUSAN · 釜山',place:'甘川文化村 · DAY 3',file:'Gamcheon Culture Village.jpg'},
 {city:'BUSAN · 釜山',place:'白浅文化村 · DAY 3',file:'Huinnyeoul culture village, Busan on October 25th, 2019.jpg'},
 {city:'SEOUL · 首尔',place:'益善洞 · DAY 4',file:'Ikseon-dong 익선동 October 1 2020 8.jpg'},
 {city:'SEOUL · 首尔',place:'景福宫 · DAY 5',file:'Gyeongbokgung Palace, Seoul, 1395 (26) (26258684237).jpg'},
 {city:'SEOUL · 首尔',place:'北村韩屋村 · DAY 5',file:'Bukchon Hanok Village Mar 2025 26.jpg'},
 {city:'SEOUL · 首尔',place:'首尔林 · DAY 6',file:'Seoul Forest 서울숲.jpg'},
 {city:'SEOUL · 首尔',place:'弘大 / 延南 · DAY 7',file:'Hongdae Street, Seoul.jpg'}
].map(x=>({...x,url:W+encodeURIComponent(x.file)+'?width=1800'}));
const hero=document.querySelector('.countdownHero');if(!hero)return;
const style=document.createElement('style');style.textContent=`.countdownHero{position:relative;padding:0!important;background:#281725!important;min-height:430px;color:#fff;border-color:#ffb7d5!important;overflow:hidden}.countdownHero:after{display:none}.heroSlides{position:absolute;inset:0;overflow:hidden;border-radius:24px}.heroSlide{position:absolute;inset:0;background-size:cover;background-position:center;opacity:0;transform:scale(1.035);transition:opacity 1.1s ease,transform 6.8s ease}.heroSlide.on{opacity:1;transform:scale(1)}.heroShade{position:absolute;inset:0;background:linear-gradient(180deg,rgba(20,7,16,.12),rgba(20,7,16,.42) 40%,rgba(20,7,16,.9))}.heroContent{position:relative;z-index:2;padding:22px 18px 17px}.countdownHero .countLabel,.countdownHero .countMeta,.countdownHero .flightTime{color:#ffe1ee}.countdownHero .countBig{color:#fff;text-shadow:0 4px 25px rgba(0,0,0,.3)}.countdownHero .flightStrip{background:rgba(255,255,255,.13);border-color:rgba(255,255,255,.24);backdrop-filter:blur(10px)}.countdownHero .flightCity{color:#fff}.countdownHero .plane{color:#ffc4dc}.heroCity{display:inline-flex;margin-bottom:5px;padding:5px 9px;border-radius:999px;background:rgba(255,255,255,.16);backdrop-filter:blur(7px);font-size:11px;font-weight:900}.heroPlace{font-size:12px;font-weight:900;color:#fff;margin:0 0 6px;text-shadow:0 2px 10px #000}.heroDots{display:flex;gap:5px;margin-top:10px}.heroDot{width:10px;height:4px;border-radius:99px;background:rgba(255,255,255,.34)}.heroDot.on{background:#fff;width:24px}.weatherWrap{position:relative;z-index:3;padding:0 14px 14px}.weatherHead{display:flex;justify-content:space-between;gap:10px;align-items:center;margin:0 2px 8px;color:#fff}.weatherSwitch{display:flex;gap:5px}.weatherSwitch button{border:1px solid rgba(255,255,255,.3);background:rgba(255,255,255,.13);color:#fff;border-radius:999px;padding:5px 8px;font-size:10px;font-weight:900}.weatherSwitch button.on{background:#fff;color:#9c3d68}.weather5{display:grid;grid-template-columns:repeat(5,minmax(72px,1fr));gap:7px;overflow:auto}.weatherDay{background:rgba(255,255,255,.92);color:#553442;border-radius:13px;padding:9px 7px;text-align:center;min-width:72px}.weatherDate{font-size:10px;color:#8b6878}.weatherIcon{font-size:21px;margin:4px 0}.weatherTemp{font-size:12px;font-weight:900;color:#7f2850}.weatherRain{font-size:9px;color:#8b6878;margin-top:3px}.weatherStatus{font-size:9px;color:#f6d7e5;margin-top:7px;text-align:right}`;document.head.appendChild(style);
const old=hero.innerHTML;hero.innerHTML=`<div class="heroSlides">${slidesData.map((x,i)=>`<div class="heroSlide ${i===0?'on':''}" style="background-image:url('${x.url}')"></div>`).join('')}<div class="heroShade"></div></div><div class="heroContent"><div class="heroCity" id="heroCity">🌊 ${slidesData[0].city}</div><div class="heroPlace" id="heroPlace">📍 ${slidesData[0].place}</div>${old}<div class="heroDots">${slidesData.map((_,i)=>`<span class="heroDot ${i===0?'on':''}"></span>`).join('')}</div></div><div class="weatherWrap"><div class="weatherHead"><b>未来 5 Days Weather</b><div class="weatherSwitch"><button class="on" data-city="Busan">釜山</button><button data-city="Seoul">首尔</button></div></div><div class="weather5" id="weather5"><div class="weatherDay">Loading…</div></div><div class="weatherStatus" id="weatherStatus">自动更新天气中…</div></div>`;
let slide=0;const slides=hero.querySelectorAll('.heroSlide'),dots=hero.querySelectorAll('.heroDot'),cityEl=hero.querySelector('#heroCity'),placeEl=hero.querySelector('#heroPlace');function show(i){slide=i;slides.forEach((x,j)=>x.classList.toggle('on',j===i));dots.forEach((x,j)=>x.classList.toggle('on',j===i));cityEl.textContent=(slidesData[i].city.startsWith('BUSAN')?'🌊 ':'🇰🇷 ')+slidesData[i].city;placeEl.textContent='📍 '+slidesData[i].place}setInterval(()=>show((slide+1)%slidesData.length),6200);
const cfg={Busan:{lat:35.1796,lon:129.0756},Seoul:{lat:37.5665,lon:126.9780}};function icon(code){if(code===0)return'☀️';if([1,2].includes(code))return'🌤️';if(code===3)return'☁️';if([45,48].includes(code))return'🌫️';if([51,53,55,61,63,65,80,81,82].includes(code))return'🌧️';if([71,73,75,77,85,86].includes(code))return'❄️';if([95,96,99].includes(code))return'⛈️';return'🌤️'}
async function loadWeather(city){document.querySelectorAll('.weatherSwitch button').forEach(b=>b.classList.toggle('on',b.dataset.city===city));const c=cfg[city],w=document.getElementById('weather5'),st=document.getElementById('weatherStatus');try{const u=`https://api.open-meteo.com/v1/forecast?latitude=${c.lat}&longitude=${c.lon}&daily=weather_code,temperature_2m_max,temperature_2m_min,precipitation_probability_max&timezone=Asia%2FSeoul&forecast_days=5`,r=await fetch(u,{cache:'no-store'}),d=await r.json(),a=d.daily;w.innerHTML=a.time.map((date,i)=>`<div class="weatherDay"><div class="weatherDate">${date.slice(5)}</div><div class="weatherIcon">${icon(a.weather_code[i])}</div><div class="weatherTemp">${Math.round(a.temperature_2m_min[i])}° / ${Math.round(a.temperature_2m_max[i])}°</div><div class="weatherRain">☔ ${a.precipitation_probability_max[i]??0}%</div></div>`).join('');st.textContent=`${city==='Busan'?'釜山':'首尔'} · Open-Meteo · 当前未来5天天气（非2027年3月预测）`}catch(e){w.innerHTML='<div class="weatherDay">天气暂时无法连接</div>';st.textContent='Weather offline'}}document.querySelectorAll('.weatherSwitch button').forEach(b=>b.onclick=()=>loadWeather(b.dataset.city));loadWeather('Busan');
})();