(()=>{
const latest=[
{d:'DAY 1 · 3/3',city:'BUSAN',title:'抵达韩国 → 直接去釜山',plan:'ICN → Seoul Station → KTX → Busan → Haeundae',rec:'06:30 抵达 ICN 后不展开首尔行程，直接转去釜山。第一天以转场、入住和海边轻松散步为主。',film:'机场清晨、AREX/KTX、车窗、Busan Station、第一次看到海。',schedule:[['06:30','抵达 ICN · 入境 / 行李'],['07:45','前往 Seoul Station'],['09:30','早餐 / KTX 准备'],['10:30','KTX Seoul → Busan'],['13:15','抵达 Busan Station'],['14:00','前往 Haeundae · 酒店寄放行李 / Check-in'],['15:30','Haeundae Beach · 轻松散步'],['17:30','Cafe / 休息'],['19:00','釜山第一餐'],['20:30','海云台夜景'],['22:00','回酒店 · 素材备份']]},
{d:'DAY 2 · 3/4',city:'BUSAN',title:'Haeundae × Blue Line × Cheongsapo',plan:'Haeundae → Blue Line Park → Sky Capsule → Cheongsapo → Sunset',rec:'完整海岸线日，重点拍 Sky Capsule、铁路、灯塔与海边情侣镜头。',film:'海浪环境音、Sky Capsule POV、车厢情侣镜头、青沙浦灯塔、海岸慢动作。',schedule:[['08:30','海云台早餐'],['09:30','Haeundae Beach · Morning Walk'],['11:00','海云台周边 / Cafe'],['12:30','午餐'],['14:00','Blue Line Park / Mipo'],['14:30','Sky Capsule · Mipo → Cheongsapo'],['15:30','Cheongsapo · 灯塔 / 海岸拍摄'],['17:30','Sunset / Cafe'],['19:00','晚餐'],['21:00','海云台夜间自由活动']]},
{d:'DAY 3 · 3/5',city:'BUSAN',title:'Gamcheon × Nampo × Jagalchi × Huinnyeoul',plan:'Gamcheon → Nampo / BIFF → Jagalchi → Huinnyeoul / Yeongdo',rec:'釜山老城与影岛故事线，也是釜山最后一个完整游玩日。',film:'甘川高低差、BIFF 街头、鱼市场环境音、影岛巷弄、海岸隧道。',schedule:[['08:30','早餐 / 出发'],['09:30','Gamcheon Culture Village'],['11:30','前往 Nampo'],['12:00','Nampo / BIFF · 午餐'],['13:30','Jagalchi Market / 港口'],['15:30','Huinnyeoul Culture Village / Yeongdo'],['17:00','Coastal Tunnel / 海岸'],['18:30','晚餐'],['20:30','回 Haeundae · 收拾行李']]},
{d:'DAY 4 · 3/6',city:'BUSAN → SEOUL',title:'KTX 回首尔 × Ikseondong × Myeongdong',plan:'Busan → KTX → Seoul → Check-in → Ikseondong → Cheonggyecheon → Myeongdong',rec:'3/6 上午离开釜山，当天就进入首尔。下午安排不需预约的市区路线，避免 KTX 延误影响。',film:'釜山 Ending、KTX 转场、Seoul Station Arrival、益善洞巷弄、首尔夜色。',schedule:[['07:30','早餐 / 最后整理'],['08:30','Busan Hotel Check-out'],['09:00','前往 Busan Station'],['10:00','KTX Busan → Seoul'],['12:45','抵达 Seoul Station'],['13:30','首尔酒店寄放行李 / Check-in'],['15:00','Ikseondong · 韩屋 / Cafe / 小店'],['17:00','Cheonggyecheon · 城市散步'],['18:30','Myeongdong · 晚餐 / Shopping'],['21:00','回酒店 · 休息']]},
{d:'DAY 5 · 3/7',city:'SEOUL',title:'韩服拍摄 × Gyeongbokgung × Bukchon',plan:'韩服租借 → 景福宫 → 北村 → 三清洞 → 西村 → 光化门',rec:'首尔主摄影日。早上先租韩服，把景福宫和北村情侣主镜头一次完成。',film:'穿戴细节、宫门正中、宫墙长焦、北村背影、袖口发饰、走路慢动作。',schedule:[['08:00','早餐'],['08:30','韩服租借 + 发型整理'],['09:00','Gyeongbokgung · 韩服主拍摄'],['10:45','Bukchon Hanok Village · 情侣拍摄'],['12:00','归还韩服 / 换便服'],['12:30','Samcheong-dong 午餐'],['14:00','Samcheong-dong Cafe / 小店'],['15:30','Seochon · 设计店 / 巷弄'],['17:30','Gwanghwamun · Blue Hour'],['19:00','韩牛 / 烤肉晚餐'],['21:00','回酒店 · 素材备份']]},
{d:'DAY 6 · 3/8',city:'SEOUL',title:'Seongsu × Seoul Forest × Hannam',plan:'Seongsu → Cafe / Pop-ups → Seoul Forest → Hannam / Itaewon',rec:'首尔现代篇，用工业建筑、咖啡、品牌店和情侣生活感与韩服日形成对比。',film:'店铺门面、咖啡细节、街头穿搭、Seoul Forest、Hannam walking shot。',schedule:[['08:30','早餐'],['09:30','Seongsu · Cafe / Shops / Pop-ups'],['12:30','Seongsu 午餐'],['14:00','Seoul Forest'],['15:30','Hannam / Itaewon'],['18:00','晚餐'],['19:30','自由夜拍 / Shopping'],['21:30','回酒店']]},
{d:'DAY 7 · 3/9',city:'SEOUL',title:'Yeonnam × Mangwon × Hongdae × Final Dinner',plan:'Yeonnam → Mangwon Market → Hongdae → Final Shopping → Final Dinner',rec:'最后完整一天保留生活感与购物，不再塞大型景点。晚上用正式 Final Dinner 收尾。',film:'延南散步、市场食物、弘大街头、Shopping haul、Final Dinner、Ending narration。',schedule:[['08:30','Yeonnam 早餐 / 散步'],['10:30','Yeonnam / 小店'],['12:00','Mangwon Market · 午餐'],['14:00','Hongdae · Shopping / Cafe'],['17:00','最后购物 / 回酒店放东西'],['19:30','Final Dinner'],['21:30','最后夜拍 / Convenience Store'],['23:00','打包 · Ending Narration']]},
{d:'DAY 8 · 3/10',city:'SEOUL → ICN',title:'回家 · ICN Departure',plan:'Hotel → ICN → Tax Refund / Breakfast → Gate → KUL',rec:'早班机不安排市区景点，优先机场交通、退税、行李与登机缓冲。',film:'清晨收行李、机场推车、登机牌、Gate、飞机窗外、Ending Shot。',schedule:[['06:00','起床 / 最后检查'],['06:30','Hotel Check-out'],['06:45','前往 ICN'],['08:00','Check-in / 行李'],['08:30','Tax Refund / 早餐 / 最后购物'],['09:45','B-roll / 前往 Gate'],['10:30','Gate'],['11:05','ICN → KUL']]}
];
function render(){try{if(typeof route==='undefined')return;route.splice(0,route.length,...latest);if(document.getElementById('routeList')&&typeof itemCard==='function')document.getElementById('routeList').innerHTML=route.map((x,i)=>`<div class="card day"><div class="time">${x.d} · ${x.city}</div><div class="place">${x.title}</div><div class="meta">${x.plan}</div><div class="rec"><b>💡 当天推荐：</b>${x.rec}</div><div class="shot">🎬 ${x.film}</div><div class="dayDetails"><button class="dayToggle" onclick="toggleDayDetail(${i})">🕒 查看 ${x.d} 详细时间表</button><div class="dayTimeline" id="timeline${i}">${x.schedule.map((s,j)=>`<div class="timeSlot"><div class="clock">${s[0]}</div><div class="what">${s[1]}</div></div>`).join('')}</div></div></div>`).join('');if(document.getElementById('dailyPreview'))document.getElementById('dailyPreview').innerHTML=route.map(x=>`<div class="card day"><div class="time">${x.d} · ${x.city}</div><div class="place">${x.title}</div><div class="meta">${x.plan}</div><div class="rec">${x.rec}</div></div>`).join('')}catch(e){console.warn('route refresh failed',e)}}
render();setTimeout(render,700);setTimeout(render,1500);
})();