(()=>{
const latest=[
{d:'DAY 1 · 3/3',city:'BUSAN',title:'抵达韩国 → 直接去釜山',plan:'ICN → 首尔站 → KTX → Busan → Haeundae',rec:'落地后不在首尔展开行程，直接完成长距离转场。抵达釜山后以入住、海云台散步和早休息为主，避免第一天排太满。',film:'机场清晨、AREX/KTX 转场、车窗、第一次看到釜山海、海云台夜色。',schedule:[['06:30','抵达 ICN · 入境 / 行李'],['07:45','前往首尔站'],['09:30','首尔站 · 早餐 / KTX 准备'],['10:30','KTX 首尔 → 釜山'],['13:15','抵达 Busan Station'],['14:00','前往酒店 · 寄放行李 / Check-in'],['15:30','海云台 Haeundae · 轻松散步'],['17:30','海景 Cafe / 休息'],['19:00','釜山第一餐 · 猪肉汤饭 / 海鲜'],['20:30','海云台夜景 · Convenience Store'],['22:00','回酒店 · 素材备份 / 休息']]},
{d:'DAY 2 · 3/4',city:'BUSAN',title:'Haeundae × Blue Line × Cheongsapo',plan:'Haeundae → Blue Line Park → Sky Capsule → Cheongsapo → 海岸日落',rec:'把釜山最有代表性的海岸线放在完整的一天。Sky Capsule 尽量安排白天至下午，海岸 B-roll 会比赶行程更有 Travel Film 感。',film:'海浪环境音、Sky Capsule POV、情侣车厢镜头、青沙浦灯塔、海岸慢动作。',schedule:[['08:30','海云台早餐'],['09:30','Haeundae Beach · Morning Walk'],['11:00','海云台周边 / Cafe'],['12:30','午餐'],['14:00','Blue Line Park / Mipo'],['14:30','Sky Capsule · Mipo → Cheongsapo'],['15:30','Cheongsapo · 灯塔 / 海岸拍摄'],['17:30','海边 Sunset / Cafe'],['19:00','晚餐'],['21:00','海云台夜间自由活动']]},
{d:'DAY 3 · 3/5',city:'BUSAN',title:'Gamcheon × Nampo × Jagalchi × Huinnyeoul',plan:'Gamcheon → Nampo / BIFF → Jagalchi → Huinnyeoul / Yeongdo',rec:'这天是釜山街区故事线：彩色山城 → 老城市场 → 港口 → 影岛海岸。以街头、食物和海岸形成画面层次。',film:'甘川高低差、市场手持、鱼市场声音、影岛巷弄、海岸隧道与情侣背影。',schedule:[['08:30','早餐 / 出发'],['09:30','Gamcheon Culture Village'],['11:30','前往 Nampo'],['12:00','Nampo / BIFF · 午餐'],['13:30','Jagalchi Market / 港口'],['15:30','Huinnyeoul Culture Village / Yeongdo'],['17:00','Huinnyeoul Coastal Tunnel / 海岸'],['18:30','回 Nampo / 晚餐'],['20:30','自由活动 / 回酒店']]},
{d:'DAY 4 · 3/6',city:'BUSAN',title:'釜山 Free Day × Gwangalli Night',plan:'自由探索 / 补拍 → Cafe → Gwangalli Sunset → 夜景',rec:'保留半天弹性，不把 4 天釜山塞满。可以补拍前几天错过的画面、睡晚一点或临时逛店；晚上以广安里作为釜山篇高潮。',film:'生活感素材、Cafe、广安大桥蓝调时刻、情侣剪影、夜景延时。',schedule:[['09:00','慢早餐 / 自由开始'],['10:30','自由探索 / 补拍 / Shopping'],['12:30','午餐'],['14:00','Cafe / 自由活动'],['16:30','前往 Gwangalli'],['17:30','Gwangalli Beach · Sunset'],['19:00','广安里晚餐'],['20:30','Gwangan Bridge Night · 主夜景拍摄'],['22:00','回酒店 · 收拾行李']]},
{d:'DAY 5 · 3/7',city:'BUSAN → SEOUL',title:'KTX 回首尔 × Seoul Afternoon',plan:'Busan → KTX → Seoul → Check-in → 下午轻松展开',rec:'上午完成釜山退房与转场，下午才正式开始首尔篇。不要安排必须预约的大景点，让转场时间有余量。',film:'釜山 Ending、KTX 转场、首尔站 Arrival、城市节奏从海边切回都市。',schedule:[['08:00','早餐 / 最后整理'],['09:00','Busan Hotel Check-out'],['09:30','前往 Busan Station'],['10:30','KTX Busan → Seoul'],['13:15','抵达 Seoul Station'],['14:00','酒店寄放行李 / Check-in'],['15:30','首尔下午自由散步 / Cafe'],['18:00','晚餐'],['19:30','首尔夜间轻松逛街'],['21:30','回酒店 · 休息']]},
{d:'DAY 6 · 3/8',city:'SEOUL',title:'韩服拍摄 × Gyeongbokgung × Bukchon',plan:'韩服租借 → 景福宫 → 北村 → 三清洞 → 西村 / 光化门',rec:'首尔主摄影日。早上先租韩服，把景福宫与北村的情侣主镜头一次完成；下午换回便服后放慢节奏。',film:'韩服穿戴、宫门正中、宫墙长焦情侣照、北村背影、袖口发饰、走路慢动作。',schedule:[['08:00','早餐'],['08:30','韩服租借 + 发型整理'],['09:00','景福宫 · 韩服主拍摄'],['10:45','北村韩屋村 · 情侣拍摄'],['12:00','归还韩服 / 换回便服'],['12:30','三清洞午餐'],['14:00','三清洞 Cafe / 小店'],['15:30','西村 / 周边慢逛'],['17:30','光化门 / 蓝调时刻'],['19:00','韩牛 / 烤肉晚餐'],['21:00','回酒店 · 素材备份']]},
{d:'DAY 7 · 3/9',city:'SEOUL',title:'Seongsu × Hannam × Shopping × Final Dinner',plan:'Seongsu → Seoul Forest → Hannam → Shopping → Final Dinner',rec:'最后完整一天用首尔最现代的城市质感收尾。白天拍 Seongsu / Hannam，晚上正式吃一顿 Final Dinner，再完成最后购物。',film:'咖啡、街头穿搭、店铺细节、首尔森林、汉南洞、购物战利品、Final Dinner 与结尾旁白。',schedule:[['08:30','早餐'],['09:30','Seongsu · Cafe / Shops / Pop-ups'],['12:00','Seongsu 午餐'],['13:30','Seoul Forest'],['15:00','Hannam / Itaewon'],['17:30','最后 Shopping / 回酒店放东西'],['19:30','Final Dinner'],['21:30','最后夜拍 / Convenience Store'],['23:00','打包 · Travel Film Ending Narration']]},
{d:'DAY 8 · 3/10',city:'SEOUL → ICN',title:'回家 · ICN Departure',plan:'Hotel → ICN → Tax Refund / Breakfast → Gate → KUL',rec:'早班机不再安排市区景点。重点是预留机场交通、退税与行李时间，Travel Film 用机场离境镜头收尾。',film:'清晨收行李、空街、机场推车、登机牌、飞机窗外、Ending Shot。',schedule:[['06:00','起床 / 最后检查'],['06:30','Hotel Check-out'],['06:45','前往 ICN'],['08:00','抵达机场 · Check-in / 行李'],['08:30','Tax Refund / 早餐 / 最后购物'],['09:45','B-roll / 前往登机口'],['10:30','Gate'],['11:05','ICN → KUL']]}
];
function apply(){
 try{
  if(typeof route==='undefined') return;
  route.splice(0,route.length,...latest);
  if(document.getElementById('routeList')&&typeof itemCard==='function') document.getElementById('routeList').innerHTML=route.map((x,i)=>`<div class="card day"><div class="time">${x.d} · ${x.city}</div><div class="place">${x.title}</div><div class="meta">${x.plan}</div><div class="rec"><b>💡 当天推荐：</b>${x.rec}</div><div class="shot">🎬 ${x.film}</div><div class="dayDetails"><button class="dayToggle" onclick="toggleDayDetail(${i})">🕒 查看 ${x.d} 详细时间表</button><div class="dayTimeline" id="timeline${i}">${x.schedule.map((s,j)=>{const noHeart=/起床|抵达 ICN|退房|前往首尔站|前往 ICN|取行李|寄放行李|Check-in|前往登机口|Gate/.test(s[1]);const hid='heart_'+i+'_'+j;const loved=localStorage.getItem(hid)==='1';return `<div class="timeSlot ${loved?'completed':''}"><div class="clock">${s[0]}</div><div class="what">${s[1]}</div>${noHeart?'':`<button class="heartCheck ${loved?'loved':''}" onclick="toggleHeart('${hid}',this)" aria-label="完成">${loved?'♥':'♡'}</button>`}</div>`}).join('')}</div></div><div style="margin-top:10px">${itemCard('day'+i,'完成这一天','走完路线并完成主要摄影素材')}</div></div>`).join('');
  if(document.getElementById('dailyPreview')) document.getElementById('dailyPreview').innerHTML=route.map(x=>`<div class="card day"><div class="time">${x.d} · ${x.city}</div><div class="place">${x.title}</div><div class="meta">${x.plan}</div><div class="rec">${x.rec}</div></div>`).join('');
  document.querySelectorAll('.hero .pill,.hero .badge,.tripMeta,.routeSummary').forEach(el=>{if(/首尔.*釜山.*首尔|Seoul.*Busan.*Seoul/i.test(el.textContent||'')) el.textContent=(el.textContent||'').replace(/首尔\s*[→×x]\s*釜山\s*[→×x]\s*首尔/gi,'釜山 → 首尔').replace(/Seoul\s*[→×x]\s*Busan\s*[→×x]\s*Seoul/gi,'Busan → Seoul')});
 }catch(e){console.warn('latest route update failed',e)}
}
apply();setTimeout(apply,700);
})();