(()=>{
const SB_URL='https://fkcwqltkrmzxmxngajdu.supabase.co';
const SB_KEY='sb_publishable_6kTH8LJXzzOuLex2iFG8qg_t-f0JZD7';
const BUCKET='korea-trip-media';
const nav=document.getElementById('tabs'),main=document.querySelector('main');
if(!nav||!main)return;

const style=document.createElement('style');style.textContent=`
.mediaStudio{margin:8px 0 18px;padding:16px;border:1px solid #f0bfd3;border-radius:18px;background:linear-gradient(145deg,#fff,#fff6fa)}.mediaTop{display:flex;justify-content:space-between;gap:10px;align-items:flex-start;flex-wrap:wrap}.mediaTop h3{margin:0 0 4px}.mediaSub{font-size:11px;color:#8c6878;line-height:1.5}.mediaControls{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:12px}.mediaControls select,.mediaControls input{width:100%;box-sizing:border-box;border:1px solid #e8b7ca;border-radius:11px;padding:10px;background:white;color:#6e3650}.uploadBtn{display:block;text-align:center;margin-top:9px;padding:11px;border-radius:12px;background:#ff5c9b;color:#fff;font-weight:900;font-size:12px;cursor:pointer}.uploadBtn input{display:none}.mediaProgress{height:7px;border-radius:99px;background:#f5dce7;overflow:hidden;margin-top:9px}.mediaProgress i{display:block;height:100%;width:0;background:#ff5c9b;transition:.25s}.mediaMsg{font-size:10px;color:#8b6878;margin-top:6px}.mediaGrid{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin-top:12px}.mediaItem{position:relative;aspect-ratio:1;border-radius:11px;overflow:hidden;background:#eadde3}.mediaItem img,.mediaItem video{width:100%;height:100%;object-fit:cover}.mediaBadge{position:absolute;left:5px;top:5px;background:#0009;color:white;border-radius:999px;padding:3px 6px;font-size:8px;font-weight:900}.mediaDel{position:absolute;right:5px;top:5px;border:0;border-radius:50%;width:25px;height:25px;background:#0009;color:white;font-size:12px}.mediaEmpty{grid-column:1/-1;padding:18px;text-align:center;color:#9a7485;font-size:11px;border:1px dashed #edbfd2;border-radius:12px}.mediaCount{font-size:11px;font-weight:900;color:#c3477b}.mediaPrivacy{margin-top:10px;padding:9px 10px;border-radius:12px;background:#fff0f6;color:#8b3f62;font-size:10px;line-height:1.5}@media(max-width:520px){.mediaControls{grid-template-columns:1fr}.mediaGrid{grid-template-columns:repeat(3,1fr)}}`;
document.head.appendChild(style);

let section=document.getElementById('media');
if(!section){section=document.createElement('section');section.className='view';section.id='media';section.innerHTML=`<h2 class="sectionTitle">私人 Travel Film 素材库</h2><div class="mediaStudio"><div class="mediaTop"><div><h3>🎞 Private Storage</h3><div class="mediaSub">照片 / 短片会进入你们这趟旅行专属的私人素材库，并按 DAY + 地点整理。</div></div><div class="mediaCount" id="mediaCount">0 files</div></div><div class="mediaControls"><select id="mediaDay">${Array.from({length:8},(_,i)=>`<option value="day${i+1}">DAY ${i+1}</option>`).join('')}</select><input id="mediaPlace" placeholder="地点 / Shot，例如 景福宫"></div><label class="uploadBtn">＋ 上载照片 / 影片<input id="mediaFiles" type="file" accept="image/jpeg,image/png,image/webp,image/heic,image/heif,video/mp4,video/quicktime,video/x-m4v" multiple></label><div class="mediaProgress"><i id="mediaBar"></i></div><div class="mediaMsg" id="mediaMsg">单个文件上限 50MB</div><div class="mediaPrivacy">🔒 Private Bucket · 必须先通过你们的 Room Key 才能读取 / 上传 / 删除。GitHub Pages 本身不会保存这些照片或影片。</div><div class="mediaGrid" id="mediaGrid"><div class="mediaEmpty">尚未上传素材</div></div></div>`;main.appendChild(section)}

let mediaTab=[...nav.querySelectorAll('button')].find(b=>b.dataset.mediaTab==='1');
if(!mediaTab){mediaTab=document.createElement('button');mediaTab.className='tab';mediaTab.dataset.mediaTab='1';mediaTab.textContent='素材库';nav.appendChild(mediaTab)}
mediaTab.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));mediaTab.classList.add('active');document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));section.classList.add('active');loadMedia()};

const H={apikey:SB_KEY,Authorization:`Bearer ${SB_KEY}`};let folderToken='';
async function getToken(){if(folderToken)return folderToken;const code=localStorage.getItem('koreaTripPrivateRoomKey');if(!code)throw new Error('请先解锁 Room Key');const r=await fetch(`${SB_URL}/rest/v1/rpc/get_trip_media_token`,{method:'POST',headers:{...H,'Content-Type':'application/json'},body:JSON.stringify({p_code:code})});if(!r.ok)throw new Error('Room Key 验证失败');folderToken=await r.json();if(!folderToken)throw new Error('Room Key 无效');return folderToken}
const clean=s=>(s||'shot').replace(/[^a-zA-Z0-9\u4e00-\u9fff._-]+/g,'-').slice(0,50);
async function loadMedia(){const g=document.getElementById('mediaGrid'),count=document.getElementById('mediaCount'),msg=document.getElementById('mediaMsg');try{const t=await getToken();msg.textContent='正在读取私人素材库…';const r=await fetch(`${SB_URL}/storage/v1/object/list/${BUCKET}`,{method:'POST',headers:{...H,'Content-Type':'application/json'},body:JSON.stringify({prefix:t+'/',limit:100,sortBy:{column:'created_at',order:'desc'}})});if(!r.ok)throw new Error('读取失败 '+r.status);let rows=await r.json();rows=rows.filter(x=>x.name&&!x.name.endsWith('/'));count.textContent=rows.length+' files';msg.textContent='✅ Private Storage 已连接';if(!rows.length){g.innerHTML='<div class="mediaEmpty">Private Storage 已连接 · 尚未上传素材</div>';return}g.innerHTML='';for(const x of rows){const path=t+'/'+x.name;const sr=await fetch(`${SB_URL}/storage/v1/object/sign/${BUCKET}/${encodeURI(path)}`,{method:'POST',headers:{...H,'Content-Type':'application/json'},body:JSON.stringify({expiresIn:3600})});if(!sr.ok)continue;const sd=await sr.json();const src=sd.signedURL&&sd.signedURL.startsWith('http')?sd.signedURL:SB_URL+'/storage/v1'+sd.signedURL;const vid=/\.(mp4|mov|m4v)$/i.test(x.name);const div=document.createElement('div');div.className='mediaItem';div.innerHTML=`${vid?`<video src="${src}" muted playsinline controls></video>`:`<img src="${src}" loading="lazy">`}<span class="mediaBadge">${x.name.split('__')[0].toUpperCase()}</span><button class="mediaDel" title="删除">×</button>`;div.querySelector('.mediaDel').onclick=()=>deleteMedia(path,x.name);g.appendChild(div)}}catch(e){g.innerHTML='<div class="mediaEmpty">Private Storage 暂时无法连接</div>';msg.textContent='⚠️ '+e.message}}
async function deleteMedia(path,name){if(!confirm('删除这个素材？\n'+name))return;const r=await fetch(`${SB_URL}/storage/v1/object/${BUCKET}/${encodeURI(path)}`,{method:'DELETE',headers:H});if(r.ok)loadMedia();else alert('删除失败，请稍后重试')}
async function uploadMedia(files){const msg=document.getElementById('mediaMsg'),bar=document.getElementById('mediaBar'),day=document.getElementById('mediaDay').value,place=clean(document.getElementById('mediaPlace').value);try{const t=await getToken();let done=0;for(const f of files){if(f.size>50*1024*1024)throw new Error(`${f.name} 超过 50MB`);const ext=(f.name.split('.').pop()||'bin').toLowerCase(),name=`${day}__${place}__${Date.now()}-${Math.random().toString(36).slice(2,7)}.${ext}`,path=`${t}/${name}`;msg.textContent=`正在上传 ${done+1}/${files.length} · ${f.name}`;const r=await fetch(`${SB_URL}/storage/v1/object/${BUCKET}/${encodeURI(path)}`,{method:'POST',headers:{...H,'Content-Type':f.type||'application/octet-stream','x-upsert':'false'},body:f});if(!r.ok){const tx=await r.text();throw new Error('上传失败 '+r.status+' '+tx.slice(0,80))}done++;bar.style.width=Math.round(done/files.length*100)+'%'}msg.textContent=`✅ 已上传 ${done} 个素材`;setTimeout(()=>bar.style.width='0',1000);await loadMedia()}catch(e){msg.textContent='⚠️ '+e.message;bar.style.width='0'}}
document.getElementById('mediaFiles').onchange=e=>{const fs=[...e.target.files];if(fs.length)uploadMedia(fs);e.target.value=''};
})();