(()=>{
const URL='https://fkcwqltkrmzxmxngajdu.supabase.co',KEY='sb_publishable_6kTH8LJXzzOuLex2iFG8qg_t-f0JZD7',BUCKET='korea-trip-media';
const camera=document.getElementById('camera');if(!camera)return;
const style=document.createElement('style');style.textContent=`
.mediaStudio{margin:14px 0 18px;padding:16px;border:1px solid #f0bfd3;border-radius:18px;background:linear-gradient(145deg,#fff,#fff6fa)}.mediaTop{display:flex;justify-content:space-between;gap:10px;align-items:flex-start;flex-wrap:wrap}.mediaTop h3{margin:0 0 4px}.mediaSub{font-size:11px;color:#8c6878;line-height:1.5}.mediaControls{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:12px}.mediaControls select,.mediaControls input{width:100%;box-sizing:border-box;border:1px solid #e8b7ca;border-radius:11px;padding:10px;background:white;color:#6e3650}.uploadBtn{display:block;text-align:center;margin-top:9px;padding:11px;border-radius:12px;background:#ff5c9b;color:#fff;font-weight:900;font-size:12px;cursor:pointer}.uploadBtn input{display:none}.mediaProgress{height:7px;border-radius:99px;background:#f5dce7;overflow:hidden;margin-top:9px}.mediaProgress i{display:block;height:100%;width:0;background:#ff5c9b;transition:.25s}.mediaMsg{font-size:10px;color:#8b6878;margin-top:6px}.mediaGrid{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin-top:12px}.mediaItem{position:relative;aspect-ratio:1;border-radius:11px;overflow:hidden;background:#eadde3}.mediaItem img,.mediaItem video{width:100%;height:100%;object-fit:cover}.mediaBadge{position:absolute;left:5px;top:5px;background:#0009;color:white;border-radius:999px;padding:3px 6px;font-size:8px;font-weight:900}.mediaDel{position:absolute;right:5px;top:5px;border:0;border-radius:50%;width:25px;height:25px;background:#0009;color:white;font-size:12px}.mediaEmpty{grid-column:1/-1;padding:18px;text-align:center;color:#9a7485;font-size:11px;border:1px dashed #edbfd2;border-radius:12px}.mediaCount{font-size:11px;font-weight:900;color:#c3477b}@media(max-width:520px){.mediaGrid{grid-template-columns:repeat(3,1fr)}}
`;document.head.appendChild(style);
const box=document.createElement('div');box.className='mediaStudio';box.innerHTML=`<div class="mediaTop"><div><h3>🎞 Travel Film 素材库</h3><div class="mediaSub">旅行当天可直接上传照片 / 短片，按 DAY + 地点整理。Derrick 与 NN 使用同一 Room Key 即可查看同一素材库。</div></div><div class="mediaCount" id="mediaCount">0 files</div></div><div class="mediaControls"><select id="mediaDay">${Array.from({length:8},(_,i)=>`<option value="day${i+1}">DAY ${i+1}</option>`).join('')}</select><input id="mediaPlace" placeholder="地点 / Shot，例如 景福宫"></div><label class="uploadBtn">＋ 上载照片 / 影片<input id="mediaFiles" type="file" accept="image/jpeg,image/png,image/webp,image/heic,image/heif,video/mp4,video/quicktime,video/x-m4v" multiple></label><div class="mediaProgress"><i id="mediaBar"></i></div><div class="mediaMsg" id="mediaMsg">单个文件上限 50MB · 建议原始大型影片仍保留在手机 / SSD，此处用于旅行素材整理与精选。</div><div class="mediaGrid" id="mediaGrid"><div class="mediaEmpty">尚未上传素材</div></div>`;
const first=camera.querySelector('.card')||camera.firstElementChild; if(first)camera.insertBefore(box,first);else camera.appendChild(box);
const H={apikey:KEY,Authorization:`Bearer ${KEY}`};let token='';
async function getToken(){if(token)return token;const code=localStorage.getItem('koreaTripPrivateRoomKey');if(!code)throw new Error('请先解锁 Room Key');const r=await fetch(`${URL}/rest/v1/rpc/get_trip_media_token`,{method:'POST',headers:{...H,'Content-Type':'application/json'},body:JSON.stringify({p_code:code})});if(!r.ok)throw new Error('Room Key 验证失败');token=await r.json();if(!token)throw new Error('Room Key 无效');return token}
const clean=s=>(s||'shot').replace(/[^a-zA-Z0-9\u4e00-\u9fff._-]+/g,'-').slice(0,50);
async function list(){const g=document.getElementById('mediaGrid'),count=document.getElementById('mediaCount');try{const t=await getToken();const r=await fetch(`${URL}/storage/v1/object/list/${BUCKET}`,{method:'POST',headers:{...H,'Content-Type':'application/json'},body:JSON.stringify({prefix:t+'/',limit:100,sortBy:{column:'created_at',order:'desc'}})});if(!r.ok)throw new Error('list '+r.status);let rows=await r.json();rows=rows.filter(x=>x.name&&!x.name.endsWith('/'));count.textContent=rows.length+' files';if(!rows.length){g.innerHTML='<div class="mediaEmpty">尚未上传素材</div>';return}g.innerHTML='';for(const x of rows){const path=t+'/'+x.name;const sr=await fetch(`${URL}/storage/v1/object/sign/${BUCKET}/${encodeURI(path)}`,{method:'POST',headers:{...H,'Content-Type':'application/json'},body:JSON.stringify({expiresIn:3600})});if(!sr.ok)continue;const sd=await sr.json(),src=sd.signedURL?.startsWith('http')?sd.signedURL:URL+'/storage/v1'+sd.signedURL;const vid=/\.(mp4|mov|m4v)$/i.test(x.name);const div=document.createElement('div');div.className='mediaItem';div.innerHTML=`${vid?`<video src="${src}" muted playsinline controls></video>`:`<img src="${src}" loading="lazy">`}<span class="mediaBadge">${x.name.split('__')[0].toUpperCase()}</span><button class="mediaDel" title="删除">×</button>`;div.querySelector('.mediaDel').onclick=()=>del(path,x.name);g.appendChild(div)}}catch(e){g.innerHTML='<div class="mediaEmpty">素材库暂时无法连接</div>';document.getElementById('mediaMsg').textContent='⚠️ '+e.message}}
async function del(path,name){if(!confirm('删除这个素材？\n'+name))return;const r=await fetch(`${URL}/storage/v1/object/${BUCKET}/${encodeURI(path)}`,{method:'DELETE',headers:H});if(r.ok)list();else alert('删除失败，请稍后重试')}
async function upload(files){const msg=document.getElementById('mediaMsg'),bar=document.getElementById('mediaBar'),day=document.getElementById('mediaDay').value,place=clean(document.getElementById('mediaPlace').value);try{const t=await getToken();let done=0;for(const f of files){if(f.size>50*1024*1024)throw new Error(`${f.name} 超过 50MB`);const ext=(f.name.split('.').pop()||'bin').toLowerCase(),name=`${day}__${place}__${Date.now()}-${Math.random().toString(36).slice(2,7)}.${ext}`,path=`${t}/${name}`;msg.textContent=`正在上传 ${done+1}/${files.length} · ${f.name}`;const r=await fetch(`${URL}/storage/v1/object/${BUCKET}/${encodeURI(path)}`,{method:'POST',headers:{...H,'Content-Type':f.type||'application/octet-stream','x-upsert':'false'},body:f});if(!r.ok){const tx=await r.text();throw new Error('上传失败 '+r.status+' '+tx.slice(0,80))}done++;bar.style.width=Math.round(done/files.length*100)+'%'}msg.textContent=`✅ 已上传 ${done} 个素材 · ${day.toUpperCase()} · ${document.getElementById('mediaPlace').value||'未命名地点'}`;setTimeout(()=>bar.style.width='0',1000);await list()}catch(e){msg.textContent='⚠️ '+e.message;bar.style.width='0'}}
document.getElementById('mediaFiles').onchange=e=>{const fs=[...e.target.files];if(fs.length)upload(fs);e.target.value=''};setTimeout(list,800);
})();