(()=>{
const $=s=>document.querySelector(s), esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const stars=n=>'★'.repeat(Math.round(n))+'☆'.repeat(5-Math.round(n));
const map=q=>'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(q);
const xhs=q=>'https://www.xiaohongshu.com/search_result?keyword='+encodeURIComponent(q);
const favKey=(type,i)=>`heart_v7_${type}_${i}`;
function favBtn(type,i){const k=favKey(type,i),on=localStorage.getItem(k)==='1';return `<button class="v7fav ${on?'on':''}" onclick="v7Fav('${k}',this)">${on?'♥':'♡'} 收藏</button>`}
window.v7Fav=(k,b)=>{const on=localStorage.getItem(k)==='1';localStorage.setItem(k,on?'0':'1');b.classList.toggle('on',!on);b.innerHTML=(!on?'♥':'♡')+' 收藏'};
const style=document.createElement('style');style.textContent=`
.v7filters{display:flex;gap:7px;overflow:auto;padding:2px 0 10px;scrollbar-width:none}.v7filters button,.v7sort{white-space:nowrap;border:1px solid #f1bfd3;background:#fff;border-radius:999px;padding:7px 10px;color:#9d3d68;font-weight:800;font-size:11px}.v7filters button.on{background:#ff5c9b;color:#fff;border-color:#ff5c9b}.v7card{position:relative}.v7top{display:flex;justify-content:space-between;gap:8px;align-items:flex-start}.v7stars{color:#d79a3c;font-weight:900;font-size:12px}.v7score{font-size:20px;font-weight:900;color:#ff5c9b}.v7addr{margin-top:7px;padding:8px;background:#fff8fb;border-radius:10px;font-size:11px;color:#75505f}.v7actions{display:flex;gap:6px;flex-wrap:wrap;margin-top:8px}.v7fav{border:1px solid #f0b9d0;background:#fff5f9;color:#b3396b;border-radius:10px;padding:7px 9px;font-size:11px;font-weight:800}.v7fav.on{background:#ff5c9b;color:white}.v7tag{display:inline-block;padding:3px 7px;border-radius:999px;background:#fff0f6;color:#ad3e70;border:1px solid #ffd0e2;font-size:10px;font-weight:800;margin:2px}.v7dayTitle{font-weight:900;color:#7f2850;margin:12px 0 7px}.dualrow{display:grid;grid-template-columns:1fr 70px 70px;gap:8px;align-items:center;padding:10px 0;border-bottom:1px dashed #f1d2df}.dualhead{font-size:11px;font-weight:900;color:#8b6878}.dualcheck{width:34px;height:34px;margin:auto;border:1px solid #e8a8c4;background:#fff;border-radius:10px;font-size:17px;color:#ff5c9b}.dualcheck.done{background:#ff5c9b;color:white}.v7progress{display:grid;grid-template-columns:1fr 1fr 1fr;gap:8px;margin-bottom:10px}.v7mini{text-align:center;background:#fff;border:1px solid #f3c7da;border-radius:14px;padding:10px}.v7mini b{display:block;color:#ff5c9b;font-size:19px}
`;document.head.appendChild(style);

const foods=[
{day:1,city:'首尔',name:'Changhwadang 益善洞店',ko:'창화당 익선점',score:4.5,must:'饺子拼盘、辣炒年糕',addr:'23 Supyo-ro 28-gil, Jongno-gu, Seoul',why:'益善洞路线内，第一天不用绕路；适合两人分食。'},
{day:1,city:'首尔',name:'益善洞冷三层肉 Mimine',ko:'익선동냉삼집 미미네',score:4.3,must:'冷冻五花肉、炒饭',addr:'Ikseon-dong, Jongno-gu, Seoul',why:'韩屋区逛完可作为韩式烤肉候选；具体门牌出发前复核。'},
{day:2,city:'首尔',name:'土俗村参鸡汤',ko:'토속촌삼계탕',score:4.7,must:'参鸡汤、海鲜葱饼',addr:'5 Jahamun-ro 5-gil, Jongno-gu, Seoul',why:'景福宫/西村动线经典组合，冷天尤其合适。'},
{day:2,city:'首尔',name:'Jongno Deungsim 益善洞店',ko:'종로등심 익선동점',score:4.5,must:'韩牛里脊、烤肉',addr:'11 Samil-daero 26-gil, Jongno-gu, Seoul',why:'想安排正式韩牛晚餐时的路线型候选。'},
{day:3,city:'首尔',name:'Gebang Sikdang Seongsu',ko:'게방식당 성수',score:4.6,must:'酱蟹套餐、韩式海鲜饭',addr:'B1F, 126 Achasan-ro, Seongdong-gu, Seoul',why:'圣水区域内，适合把传统韩味放进潮流街区日。'},
{day:3,city:'首尔',name:'Lazy Yogurt Seongsu',ko:'레이지요거트 성수',score:4.2,must:'希腊酸奶、季节水果碗',addr:'48 Ttukseom-ro 17ga-gil, Seongdong-gu, Seoul',why:'轻早餐/咖啡替代选项，不影响圣水逛店节奏。'},
{day:4,city:'首尔',name:'Myth Jokbal 弘大本店',ko:'미쓰족발 홍대본점',score:4.5,must:'猪蹄、蒜香猪蹄',addr:'123-1 Eoulmadang-ro, Mapo-gu, Seoul',why:'弘大晚餐方便，适合两人共享。'},
{day:4,city:'首尔',name:'望远市场',ko:'망원시장',score:4.6,must:'炸鸡块、可乐饼、鱼糕、紫菜包饭',addr:'14 Poeun-ro 8-gil, Mapo-gu, Seoul',why:'不要只吃一家；少量多样最适合拍食物素材。'},
{day:5,city:'釜山',name:'Pohang Dwaeji Gukbap',ko:'포항돼지국밥',score:4.7,must:'猪肉汤饭、白切猪肉套餐',addr:'25 Seomyeon-ro 68beon-gil, Busanjin-gu, Busan',why:'超过50年传统，釜山代表性第一餐候选。'},
{day:5,city:'釜山',name:'Songjeong Samdae Gukbap',ko:'송정3대국밥',score:4.7,must:'猪肉汤饭、Suyuk Baekban',addr:'33 Seomyeon-ro 68beon-gil, Busanjin-gu, Busan',why:'西面猪肉汤饭街老店，适合与 Pohang 二选一。'},
{day:5,city:'釜山',name:'Choryang Milmyeon',ko:'초량밀면',score:4.4,must:'水冷面、拌冷面、饺子',addr:'225 Jungang-daero, Dong-gu, Busan',why:'靠近釜山站，KTX 抵达或返程前非常顺路。'},
{day:6,city:'釜山',name:'Geodae Dwaeji Gukbap',ko:'거대돼지국밥',score:4.8,must:'浓汤猪肉汤饭、白切肉',addr:'16-2 Dalmaji-gil, Haeundae-gu, Busan',why:'海云台区域高优先级猪肉汤饭候选。'},
{day:6,city:'釜山',name:'Anmok',ko:'안목',score:4.8,must:'猪肉汤饭、猪肉拉面、白切肉',addr:'3 Gwangnam-ro 22beon-gil, Suyeong-gu, Busan',why:'广安里附近，Michelin Bib Gourmand 路线型选择。'},
{day:6,city:'釜山',name:'Subyeon Choego Dwaejigukbap',ko:'수변최고돼지국밥',score:4.7,must:'Hangjeong Gukbap、猪肉汤饭',addr:'9-32 Gwanganhaebyeon-ro 370beon-gil, Suyeong-gu, Busan',why:'靠近广安里/民乐水边，夜景前后可安排。'},
{day:7,city:'釜山',name:'Naeho Naengmyeon',ko:'내호냉면',score:4.6,must:'Milmyeon、Bibim Milmyeon',addr:'17 Uambeonyeong-ro 26beon-gil, Nam-gu, Busan',why:'釜山小麦冷面历史型选择，适合最后一餐候选。'}
];
const spots=[
{day:1,name:'益善洞韩屋街',score:4.7,photo:4.8,couple:4.8,addr:'Ikseon-dong, Jongno-gu, Seoul',best:'11:00前后 / 傍晚',stay:'1.5–2h',type:'韩屋·街拍',tip:'窄巷纵深、韩屋门框、咖啡窗边情侣照'},
{day:1,name:'清溪川',score:4.2,photo:4.2,couple:4.3,addr:'Cheonggyecheon-ro, Jongno-gu, Seoul',best:'蓝调时刻',stay:'45–60m',type:'城市·散步',tip:'低机位流水前景 + 城市灯光'},
{day:1,name:'明洞霓虹街区',score:4.4,photo:4.5,couple:4.2,addr:'Myeongdong-gil, Jung-gu, Seoul',best:'19:00后',stay:'1.5–2h',type:'夜景·街拍',tip:'霓虹、街食、人群压缩感'},
{day:2,name:'景福宫',score:5.0,photo:5.0,couple:4.9,addr:'161 Sajik-ro, Jongno-gu, Seoul',best:'开门后尽早',stay:'2–3h',type:'必去·宫殿',tip:'光化门正中、宫墙长焦、韩服情侣镜头'},
{day:2,name:'北村韩屋村',score:4.7,photo:4.9,couple:4.7,addr:'37 Gyedong-gil, Jongno-gu, Seoul',best:'上午',stay:'1–1.5h',type:'韩屋·出片',tip:'上坡背影与屋檐层次；居民区保持安静'},
{day:2,name:'昌德宫',score:4.7,photo:4.8,couple:4.6,addr:'99 Yulgok-ro, Jongno-gu, Seoul',best:'上午/下午柔光',stay:'1.5–2h',type:'宫殿·建筑',tip:'红门、屋檐、庭院对称构图'},
{day:2,name:'德寿宫石墙路',score:4.4,photo:4.7,couple:4.8,addr:'99 Sejong-daero, Jung-gu, Seoul',best:'傍晚',stay:'45m',type:'情侣·街拍',tip:'石墙长焦压缩 + 并肩走路'},
{day:3,name:'圣水洞',score:4.9,photo:4.9,couple:4.7,addr:'Seongsu-dong 2-ga, Seongdong-gu, Seoul',best:'10:00–16:00',stay:'3–4h',type:'网红·潮流',tip:'工业建筑、Popup 门面、咖啡细节'},
{day:3,name:'首尔林',score:4.5,photo:4.7,couple:4.8,addr:'273 Ttukseom-ro, Seongdong-gu, Seoul',best:'下午',stay:'1–1.5h',type:'自然·情侣',tip:'步道跟拍、长椅、树影逆光'},
{day:3,name:'汉南洞',score:4.6,photo:4.7,couple:4.6,addr:'Hannam-dong, Yongsan-gu, Seoul',best:'15:00后',stay:'1.5–2h',type:'潮流·街拍',tip:'坡道、精品店门面、极简建筑'},
{day:3,name:'盘浦汉江公园',score:4.8,photo:4.9,couple:5.0,addr:'40 Sinbanpo-ro 11-gil, Seocho-gu, Seoul',best:'日落→蓝调',stay:'1.5–2h',type:'夜景·情侣',tip:'远景剪影、便利店拉面、城市环境声'},
{day:4,name:'延南洞 / 京义线森林公园',score:4.6,photo:4.7,couple:4.9,addr:'Gyeongui Line Forest Park, Mapo-gu, Seoul',best:'上午',stay:'1.5h',type:'情侣·生活感',tip:'散步跟拍、街角咖啡、自然互动'},
{day:4,name:'望远市场',score:4.5,photo:4.3,couple:4.3,addr:'14 Poeun-ro 8-gil, Mapo-gu, Seoul',best:'午餐时段',stay:'1–1.5h',type:'市场·人文',tip:'食物 close-up、摊主动作、边走边吃'},
{day:4,name:'弘大步行街',score:4.4,photo:4.5,couple:4.4,addr:'Hongik-ro, Mapo-gu, Seoul',best:'傍晚/夜间',stay:'2h',type:'街头·夜景',tip:'街头表演、霓虹、手持 Vlog'},
{day:5,name:'甘川文化村',score:4.8,photo:5.0,couple:4.7,addr:'203 Gamnae 2-ro, Saha-gu, Busan',best:'下午柔光',stay:'2–3h',type:'必去·出片',tip:'彩色屋顶 wide reveal、阶梯巷弄；尊重居民'},
{day:5,name:'BIFF 广场',score:4.2,photo:4.2,couple:4.0,addr:'58-1 Gudeok-ro, Jung-gu, Busan',best:'傍晚',stay:'45–60m',type:'街头·美食',tip:'招牌、热食蒸汽、手持移动镜头'},
{day:5,name:'札嘎其市场',score:4.4,photo:4.4,couple:4.0,addr:'52 Jagalchihaean-ro, Jung-gu, Busan',best:'傍晚',stay:'1–1.5h',type:'市场·港口',tip:'海鲜、港口、人文细节'},
{day:6,name:'海云台海水浴场',score:4.8,photo:4.8,couple:4.9,addr:'264 Haeundaehaebyeon-ro, Haeundae-gu, Busan',best:'早晨',stay:'1–1.5h',type:'海景·情侣',tip:'海浪前景、人物侧脸、沙滩脚印'},
{day:6,name:'青沙浦',score:4.9,photo:5.0,couple:4.8,addr:'Cheongsapo-ro, Haeundae-gu, Busan',best:'14:00–17:00',stay:'2h',type:'网红·列车',tip:'固定机位等列车穿画；不要站入轨道'},
{day:6,name:'广安里海水浴场',score:5.0,photo:5.0,couple:5.0,addr:'219 Gwanganhaebyeon-ro, Suyeong-gu, Busan',best:'日落前60–90m到场',stay:'2–3h',type:'必去·夜景',tip:'蓝调广安大桥 + 情侣剪影'},
{day:7,name:'白浅文化村 / Huinnyeoul',score:4.9,photo:5.0,couple:4.9,addr:'Huinnyeoul-gil, Yeongdo-gu, Busan',best:'上午',stay:'2h',type:'海岸·出片',tip:'悬崖小路跟拍、海岸慢走、旁白'},
{day:7,name:'白浅海岸隧道',score:4.6,photo:4.9,couple:4.7,addr:'1210-38 Yeongseon-dong 4-ga, Yeongdo-gu, Busan',best:'上午',stay:'30–45m',type:'网红·构图',tip:'隧道框景拍海面剪影'},
{day:8,name:'仁川机场 Ending Spot',score:4.2,photo:4.3,couple:4.4,addr:'Incheon International Airport',best:'登机前',stay:'20m',type:'影片收尾',tip:'行李、航班屏、窗边飞机、最终旁白'}
];
const buys=[
{day:1,name:'Olive Young K-Beauty 补货',cat:'美妆',score:5.0,price:'按当日活动价',tax:'认证门店可退税；结账出示护照',where:'明洞 Olive Young / 路线内大型门店',addr:'Myeongdong-gil, Jung-gu, Seoul',deal:'韩国门店通常选择最多；先买核心品，DAY 7 再补货'},
{day:1,name:'面膜 / 防晒 / 护发',cat:'护肤',score:4.8,price:'出发前30天核价',tax:'多数 Tax Refund 门店可办理',where:'Olive Young',addr:'Myeongdong-gil, Jung-gu, Seoul',deal:'韩国促销套装常有优势；不要只看单件标价'},
{day:2,name:'韩国传统工艺 / 文创',cat:'伴手礼',score:4.5,price:'₩10,000 起常见',tax:'National Souvenirs Center 支持即时退税',where:'Korea Tourism Souvenir Store',addr:'14 Insadong 5-gil, Jongno-gu, Seoul',deal:'比普通游客纪念品更有韩国特色'},
{day:3,name:'TAMBURINS 香氛',cat:'香氛',score:4.8,price:'出发前30天核价',tax:'视购买门店 Tax Refund 标识',where:'圣水 / 新沙品牌店；免税店同步比价',addr:'Seongsu-dong, Seongdong-gu, Seoul',deal:'先试香；市区活动价 vs Duty Free 当天比较'},
{day:3,name:'NONFICTION 香氛 / Body Care',cat:'香氛',score:4.6,price:'出发前30天核价',tax:'视门店',where:'汉南区域品牌店',addr:'Hannam-dong, Yongsan-gu, Seoul',deal:'适合情侣纪念品；不要盲买大容量'},
{day:3,name:'圣水限定 Popup / 韩国设计品牌',cat:'韩国限定',score:4.7,price:'依品牌',tax:'依门店',where:'圣水',addr:'Seongsu-dong, Seongdong-gu, Seoul',deal:'限定性高，看到真正喜欢的可当天买，不等机场'},
{day:4,name:'韩国设计文具 / Sticker',cat:'文具',score:4.5,price:'₩2,000–30,000 常见',tax:'小店不一定支持',where:'延南 / 弘大',addr:'Yeonnam-dong, Mapo-gu, Seoul',deal:'轻、好带，适合送人'},
{day:4,name:'韩国零食第一轮',cat:'零食',score:4.2,price:'超市/便利店当日价',tax:'视门店与金额',where:'望远市场 / 大型超市',addr:'Mapo-gu, Seoul',deal:'先试吃，不要 DAY 4 就买大量重货'},
{day:5,name:'釜山限定 Gamcheon Patch / 文创',cat:'釜山限定',score:4.7,price:'依商品',tax:'依店铺',where:'甘川文化村',addr:'203 Gamnae 2-ro, Saha-gu, Busan',deal:'釜山限定比普通 Seoul souvenir 更有纪念意义'},
{day:6,name:'海云台 / 广安里本地设计饰品',cat:'饰品',score:4.4,price:'依商品',tax:'依店铺',where:'Haeridan-gil / Gwangalli',addr:'15-1 Udong 1-ro 38beon-gil, Haeundae-gu, Busan',deal:'优先买小件、当地限定'},
{day:7,name:'伴手礼集中补货',cat:'伴手礼',score:4.8,price:'按清单',tax:'大型 Tax Refund 门店优先',where:'明洞 / 弘大',addr:'Seoul',deal:'最后一晚按 Checklist 补齐，避免遗漏'},
{day:8,name:'机场 Duty Free 高单价品',cat:'免税',score:4.6,price:'当天 Duty Free 价',tax:'Duty Free 已免税',where:'ICN 出境区',addr:'Incheon International Airport',deal:'香水/高单价品牌可与市区退税后价格比较再决定'},
{day:8,name:'Olive Young 机场最后补货',cat:'美妆',score:4.0,price:'当天门店价',tax:'机场门店可依规则退税',where:'ICN T1/T2 B1 Olive Young',addr:'271 Gonghang-ro / 444 Je2teomineol-daero, Incheon',deal:'只补漏；热门货库存不确定，不建议把核心采购拖到机场'}
];
const cameraDays={
1:['Video｜KUL 机场推行李低机位','Video｜飞机窗外 + ICN Arrival Board','Video｜AREX/机场巴士转场','Photo｜益善洞韩屋情侣照','Couple｜NN 走巷子的背影','Audio｜清溪川流水与城市声','Video｜明洞霓虹 + 街头食物','Transition｜酒店门开关 match cut','Narration｜第一次看到首尔的感受','Ending｜便利店/酒店窗外收尾'],
2:['Video｜景福宫开门 establishing','Photo｜宫墙情侣长焦','Couple｜并肩穿过宫门','Video｜北村上坡背影','Photo｜三清洞咖啡窗边','Audio｜韩屋巷自然环境声','Transition｜宫门→咖啡门','Video｜西村小店细节','Photo｜光化门蓝调','Narration｜传统首尔的一天'],
3:['Video｜地铁到圣水转场','Video｜Popup/招牌快速 montage','Photo｜工业建筑街拍','Video｜咖啡制作 close-up','Couple｜首尔林自然互动','Photo｜汉南极简门面','Transition｜白天→汉江夕阳','Audio｜汉江风声/自行车','Couple｜汉江远景剪影','Narration｜现代首尔的节奏'],
4:['Video｜延南早晨 walking vlog','Photo｜小店/文具 flatlay','Video｜望远市场食物 close-up','Audio｜市场叫卖声','Couple｜边走边吃','Video｜弘大街头表演','Photo｜霓虹街拍','Transition｜购物袋 whip pan','Video｜回酒店整理行李','Narration｜首尔前半段总结'],
5:['Video｜首尔站时钟/车票','Transition｜KTX 门关闭','Video｜高速窗景','Video｜Busan Station reveal','Food｜第一碗猪肉汤饭','Video｜甘川屋顶 wide reveal','Couple｜彩色巷弄跟拍','Audio｜南浦街头声','Video｜札嘎其海鲜细节','Narration｜城市节奏开始变慢'],
6:['Video｜海云台海浪慢镜','Photo｜沙滩情侣侧影','Video｜Blue Line 列车穿画','Photo｜青沙浦灯塔/海岸','Audio｜海浪纯环境声30秒','Transition｜列车→广安大桥','Video｜日落 timelapse','Couple｜蓝调剪影','Video｜广安里夜景主镜头','Narration｜全片情绪高潮'],
7:['Video｜白浅海岸慢走','Photo｜隧道框景情侣照','Audio｜海风 + 脚步','Narration｜旅行快结束的感受','Transition｜Busan Station→KTX','Video｜返程窗外','Video｜首尔最后晚餐','Couple｜最后一晚合照','Video｜打包/购物袋 montage','Ending｜酒店夜景'],
8:['Video｜收行李 close-up','Video｜清晨首尔街道','Transition｜酒店门→机场门','Video｜ICN 航班屏','Photo｜两人+行李最后合照','Audio｜机场广播','Video｜退税/早餐 B-roll','Video｜登机口飞机','Narration｜最终 ending 旁白','Final｜飞机起飞窗外 8–10 秒']};
const checks=[
['证件','护照有效期 / 空白页'],['证件','机票电子票离线保存'],['证件','旅游保险文件'],['证件','韩国入境要求出发前复核'],['预订','首尔前4晚酒店'],['预订','釜山2晚酒店'],['预订','首尔最后1晚酒店'],['预订','KTX 首尔→釜山'],['预订','KTX 釜山→首尔'],['预订','Blue Line / 热门项目预约'],['网络','eSIM / Roaming'],['付款','海外信用卡功能开启'],['付款','备用卡'],['付款','KRW 现金'],['Apps','Naver Map 收藏夹'],['Apps','Papago / 翻译工具'],['行李','韩国插头转换器'],['行李','Powerbank'],['行李','充电线 / 多口充电器'],['摄影','手机容量清理'],['摄影','相机 / 镜头 / 电池'],['摄影','备用存储 / 云端备份'],['摄影','每天素材备份规则'],['购物','必买清单确认'],['购物','退税商品保留收据'],['购物','最后一晚补货检查'],['回程','确认 ICN 航站楼'],['回程','Tax Refund 流程'],['回程','行李重量'],['回程','机场交通时间确认']];
let filter={food:{day:0,star:0,fav:false},spot:{day:0,star:0,fav:false},buy:{day:0,star:0,fav:false}};
function controls(type){return `<div class="v7filters" id="${type}Days"><button class="on" data-v="0">全部</button>${[1,2,3,4,5,6,7,8].map(d=>`<button data-v="${d}">DAY ${d}</button>`).join('')}</div><div class="v7filters" id="${type}Stars"><button class="on" data-v="0">全部星级</button><button data-v="5">★★★★★</button><button data-v="4">★★★★+</button><button data-v="3">★★★+</button><button data-v="fav">♥ 收藏</button><button data-v="sort">推荐度 ↓</button></div>`}
function wire(type,render){document.querySelectorAll(`#${type}Days button`).forEach(b=>b.onclick=()=>{document.querySelectorAll(`#${type}Days button`).forEach(x=>x.classList.remove('on'));b.classList.add('on');filter[type].day=+b.dataset.v;render()});document.querySelectorAll(`#${type}Stars button`).forEach(b=>b.onclick=()=>{if(b.dataset.v==='sort'){filter[type].desc=!filter[type].desc;b.textContent=filter[type].desc===false?'推荐度 ↑':'推荐度 ↓'}else if(b.dataset.v==='fav'){filter[type].fav=!filter[type].fav;b.classList.toggle('on',filter[type].fav)}else{document.querySelectorAll(`#${type}Stars button[data-v="0"],#${type}Stars button[data-v="3"],#${type}Stars button[data-v="4"],#${type}Stars button[data-v="5"]`).forEach(x=>x.classList.remove('on'));b.classList.add('on');filter[type].star=+b.dataset.v}render()})}
function filtered(arr,type){let a=arr.map((x,i)=>({...x,_i:i})).filter(x=>(!filter[type].day||x.day===filter[type].day)&&(!filter[type].star||x.score>=filter[type].star)&&(!filter[type].fav||localStorage.getItem(favKey(type,x._i))==='1'));return a.sort((a,b)=>(filter[type].desc===false?a.score-b.score:b.score-a.score))}
function renderFood(){const el=$('#foodList');if(!el)return;const first=!$('#foodV7Ctl');if(first)el.insertAdjacentHTML('beforebegin',`<div id="foodV7Ctl">${controls('food')}</div>`);el.innerHTML=filtered(foods,'food').map(x=>`<div class="card v7card"><div class="v7top"><div><span class="v7tag">DAY ${x.day}</span><span class="v7tag">${x.city}</span><h3>${esc(x.name)} <span class="small">${esc(x.ko)}</span></h3></div><div><div class="v7score">${x.score.toFixed(1)}</div><div class="v7stars">${stars(x.score)}</div></div></div><div class="meta"><b>🍽️ 必点：</b>${esc(x.must)}<br><b>💡 推荐：</b>${esc(x.why)}</div><div class="v7addr">📍 ${esc(x.addr)}</div><div class="v7actions"><a class="mapBtn" target="_blank" href="${map(x.addr)}">📍 地图</a><a class="mapBtn" target="_blank" href="${xhs(x.name+' 韩国')}">📕 小红书</a>${favBtn('food',x._i)}</div></div>`).join('')||'<div class="card small">没有符合筛选条件的推荐。</div>';if(first)wire('food',renderFood)}
function renderSpot(){const el=$('#spotList');if(!el)return;const first=!$('#spotV7Ctl');if(first)el.insertAdjacentHTML('beforebegin',`<div id="spotV7Ctl">${controls('spot')}</div>`);el.innerHTML=filtered(spots,'spot').map(x=>`<div class="card v7card"><div class="v7top"><div><span class="v7tag">DAY ${x.day}</span><span class="v7tag">${esc(x.type)}</span><h3>${esc(x.name)}</h3></div><div><div class="v7score">${x.score.toFixed(1)}</div><div class="v7stars">${stars(x.score)}</div></div></div><div class="meta">📸 出片 <b>${x.photo.toFixed(1)}</b> · ❤️ 情侣 <b>${x.couple.toFixed(1)}</b><br>⏱️ ${esc(x.stay)} · 🕐 ${esc(x.best)}<br>🎬 ${esc(x.tip)}</div><div class="v7addr">📍 ${esc(x.addr)}</div><div class="v7actions"><a class="mapBtn" target="_blank" href="${map(x.addr)}">📍 地图</a><a class="mapBtn" target="_blank" href="${xhs(x.name+' 韩国 拍照')}">📕 小红书</a>${favBtn('spot',x._i)}</div></div>`).join('')||'<div class="card small">没有符合筛选条件的推荐。</div>';if(first)wire('spot',renderSpot)}
function renderBuy(){const el=$('#buyList');if(!el)return;const first=!$('#buyV7Ctl');if(first)el.insertAdjacentHTML('beforebegin',`<div class="card small"><b>🧾 韩国退税提示：</b>认证 Tax Refund 店一般单笔满 ₩15,000 才符合条件；即时退税及总额有上限。价格/活动/门店资格请在出发前30天再次核实。</div><div id="buyV7Ctl">${controls('buy')}</div>`);el.innerHTML=filtered(buys,'buy').map(x=>`<div class="card v7card"><div class="v7top"><div><span class="v7tag">DAY ${x.day}</span><span class="v7tag">${esc(x.cat)}</span><h3>${esc(x.name)}</h3></div><div><div class="v7score">${x.score.toFixed(1)}</div><div class="v7stars">${stars(x.score)}</div></div></div><div class="meta">💰 ${esc(x.price)}<br>🧾 ${esc(x.tax)}<br>🏪 ${esc(x.where)}<br>💡 <b>${esc(x.deal)}</b></div><div class="v7addr">📍 ${esc(x.addr)}</div><div class="v7actions"><a class="mapBtn" target="_blank" href="${map(x.addr)}">📍 地图</a><a class="mapBtn" target="_blank" href="${xhs(x.name+' 韩国 价格')}">📕 小红书</a>${favBtn('buy',x._i)}</div></div>`).join('')||'<div class="card small">没有符合筛选条件的推荐。</div>';if(first)wire('buy',renderBuy)}
function renderCamera(){const el=$('#cameraList');if(!el)return;el.innerHTML=Object.entries(cameraDays).map(([d,arr])=>`<div class="v7dayTitle">DAY ${d} · 今日必拍 ${arr.length} 镜头</div>${arr.map((s,i)=>{const id=`camv7_${d}_${i}`,done=localStorage.getItem(id)==='1';return `<div class="card"><div class="row"><button class="check ${done?'done':''}" onclick="v7Check('${id}',this)">${done?'✓':''}</button><div class="grow"><h3 class="${done?'doneText':''}">${esc(s)}</h3><div class="small">拍完立即打勾 · 双人云端同步</div></div></div></div>`}).join('')}`).join('')}
window.v7Check=(id,b)=>{const on=localStorage.getItem(id)==='1';localStorage.setItem(id,on?'0':'1');b.classList.toggle('done',!on);b.textContent=!on?'✓':'';const h=b.parentElement.querySelector('h3');if(h)h.classList.toggle('doneText',!on)};
function renderChecks(){const el=$('#checkList');if(!el)return;const stats=who=>checks.filter((_,i)=>localStorage.getItem(`checkv7_${who}_${i}`)==='1').length;const a=stats('d'),b=stats('n'),n=checks.length,all=a+b;el.innerHTML=`<div class="v7progress"><div class="v7mini">Derrick<b>${Math.round(a/n*100)}%</b>${a}/${n}</div><div class="v7mini">NN<b>${Math.round(b/n*100)}%</b>${b}/${n}</div><div class="v7mini">💗 Couple<b>${Math.round(all/(n*2)*100)}%</b>${all}/${n*2}</div></div><div class="card"><div class="dualrow dualhead"><div>CHECKPOINT</div><div>Derrick</div><div>NN</div></div>${checks.map((x,i)=>{const kd=`checkv7_d_${i}`,kn=`checkv7_n_${i}`,d=localStorage.getItem(kd)==='1',n1=localStorage.getItem(kn)==='1';return `<div class="dualrow"><div><b>${esc(x[1])}</b><div class="small">${esc(x[0])}</div></div><button class="dualcheck ${d?'done':''}" onclick="v7Dual('${kd}',this)">${d?'✓':'○'}</button><button class="dualcheck ${n1?'done':''}" onclick="v7Dual('${kn}',this)">${n1?'✓':'○'}</button></div>`}).join('')}</div>`}
window.v7Dual=(id,b)=>{const on=localStorage.getItem(id)==='1';localStorage.setItem(id,on?'0':'1');renderChecks()};
// 修复旧版 checkbox 立即 reload 可能中断云端写入的问题
window.toggle=async id=>{const v=localStorage.getItem(id)==='1';localStorage.setItem(id,v?'0':'1');if(typeof cloudWrite==='function')await cloudWrite();location.reload()};
renderFood();renderSpot();renderBuy();renderCamera();renderChecks();
})();